// ======================================================================
// \title  MessageStorageTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for MessageStorage component test harness helper functions
// ======================================================================

#include "MessageStorageTester.hpp"

namespace MessageModule {

// ----------------------------------------------------------------------
// Helper functions
// ----------------------------------------------------------------------

void MessageStorageTester ::connectPorts() {
  // Connect special output ports

  this->component.set_eventOut_OutputPort(0, this->get_from_eventOut(0));

  this->component.set_textEventOut_OutputPort(0,
                                              this->get_from_textEventOut(0));

  this->component.set_timeGetOut_OutputPort(0, this->get_from_timeGetOut(0));

  this->component.set_tlmOut_OutputPort(0, this->get_from_tlmOut(0));

  // Connect typed input ports

  this->connect_to_loadMessageFromIndex(
      0, this->component.get_loadMessageFromIndex_InputPort(0));

  this->connect_to_loadMessageLastN(
      0, this->component.get_loadMessageLastN_InputPort(0));

  this->connect_to_storeMessage(0,
                                this->component.get_storeMessage_InputPort(0));
}

void MessageStorageTester ::initComponents() {
  this->init();
  this->component.init(MessageStorageTester::TEST_INSTANCE_ID);
}

} // namespace MessageModule
