// ======================================================================
// \title  FppConstantsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FPP constants
// ======================================================================

#ifndef Components_StateMachine_FppConstantsAc_HPP
#define Components_StateMachine_FppConstantsAc_HPP

#include "FpConfig.hpp"

namespace StateMachineModule {

  //! Variables
  enum FppConstant_StateMachine_initNumConnections {
    StateMachine_initNumConnections = 2
  };

}

#endif
