// ======================================================================
// \title  FileRecyclerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FileRecycler component test harness helper functions
// ======================================================================

#include "FileRecyclerTester.hpp"

namespace FileRecyclerModule {

// ----------------------------------------------------------------------
// Helper functions
// ----------------------------------------------------------------------

void FileRecyclerTester ::connectPorts() {
  // Connect special input ports

  this->connect_to_cmdIn(0, this->component.get_cmdIn_InputPort(0));

  // Connect special output ports

  this->component.set_cmdRegOut_OutputPort(0, this->get_from_cmdRegOut(0));

  this->component.set_cmdResponseOut_OutputPort(
      0, this->get_from_cmdResponseOut(0));

  this->component.set_eventOut_OutputPort(0, this->get_from_eventOut(0));

  this->component.set_prmGetOut_OutputPort(0, this->get_from_prmGetOut(0));

  this->component.set_prmSetOut_OutputPort(0, this->get_from_prmSetOut(0));

  this->component.set_textEventOut_OutputPort(0,
                                              this->get_from_textEventOut(0));

  this->component.set_timeGetOut_OutputPort(0, this->get_from_timeGetOut(0));

  this->component.set_tlmOut_OutputPort(0, this->get_from_tlmOut(0));

  // Connect typed input ports

  this->connect_to_cleanupDataPathRecv(
      0, this->component.get_cleanupDataPathRecv_InputPort(0));

  this->connect_to_fileRecyclerOpIn(
      0, this->component.get_fileRecyclerOpIn_InputPort(0));

  this->connect_to_readyForPowerOff(
      0, this->component.get_readyForPowerOff_InputPort(0));

  this->connect_to_scheduledHandler(
      0, this->component.get_scheduledHandler_InputPort(0));

  // Connect typed output ports

  this->component.set_sendSchedule_OutputPort(0,
                                              this->get_from_sendSchedule(0));

  this->component.set_toFileRecyclerHandler_OutputPort(
      0, this->get_from_toFileRecyclerHandler(0));
}

void FileRecyclerTester ::initComponents() {
  this->init();
  this->component.init(FileRecyclerTester::TEST_INSTANCE_QUEUE_DEPTH,
                       FileRecyclerTester::TEST_INSTANCE_ID);
}

} // namespace FileRecyclerModule
