// ======================================================================
// \title  SchedulerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Scheduler component test harness helper functions
// ======================================================================

#include "SchedulerTester.hpp"

namespace SchedulerModule {

// ----------------------------------------------------------------------
// Helper functions
// ----------------------------------------------------------------------

void SchedulerTester ::connectPorts() {
  // Connect special input ports

  this->connect_to_cmdIn(0, this->component.get_cmdIn_InputPort(0));

  // Connect special output ports

  this->component.set_cmdRegOut_OutputPort(0, this->get_from_cmdRegOut(0));

  this->component.set_cmdResponseOut_OutputPort(
      0, this->get_from_cmdResponseOut(0));

  this->component.set_eventOut_OutputPort(0, this->get_from_eventOut(0));

  this->component.set_textEventOut_OutputPort(0,
                                              this->get_from_textEventOut(0));

  this->component.set_timeGetOut_OutputPort(0, this->get_from_timeGetOut(0));

  this->component.set_tlmOut_OutputPort(0, this->get_from_tlmOut(0));

  // Connect typed input ports

  for (FwIndexType i = 0; i < 3; i++) {
    this->connect_to_getSchedule(i,
                                 this->component.get_getSchedule_InputPort(i));
  }

  this->connect_to_tick(0, this->component.get_tick_InputPort(0));

  // Connect typed output ports

  this->component.set_downlinkCurrentSchedules_OutputPort(
      0, this->get_from_downlinkCurrentSchedules(0));

  for (FwIndexType i = 0; i < 3; i++) {
    this->component.set_runSchedule_OutputPort(i,
                                               this->get_from_runSchedule(i));
  }
}

void SchedulerTester ::initComponents() {
  this->init();
  this->component.init(SchedulerTester::TEST_INSTANCE_QUEUE_DEPTH,
                       SchedulerTester::TEST_INSTANCE_ID);
}

} // namespace SchedulerModule
