// ======================================================================
// \title  FppConstantsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FPP constants
// ======================================================================

#ifndef Components_Scheduler_FppConstantsAc_HPP
#define Components_Scheduler_FppConstantsAc_HPP

#include "FpConfig.hpp"

namespace SchedulerModule {

  //! Variables
  enum FppConstant_Scheduler_initNumConnections {
    Scheduler_initNumConnections = 3
  };

}

#endif
